scrape_configs:
  - job_name: 'SpringMonitoringApplication'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'SpringMonitoringApplication'
#  - job_name: 'prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ '127.0.0.1:9090' ]
